### ISSUE TITLE
Module is active when other payment methods were chosen  

### ISSUE THREAD

**Issue by biojppm** [manuelrocha88/magento2-Ifthenpay_Multibanco#2]
When I finalize an order with other payment methods (eg Braintree credit card or Braintree paypal), I get a generated multibanco reference table even though Multibanco was not selected. See the print screen below. It was obtained as the result of the credit card payment confirmation. I am in sandbox mode, and the sort order is Multibanco-1 Braintree-2.

![ifthenpay_bug](https://cloud.githubusercontent.com/assets/325344/18030664/5727360e-6cb6-11e6-8630-060c8bccf178.png)

**Comment by biojppm** [comment]
It gets worse. This still happens even after I deactivate the Multibanco payment mode in the Magento config (ie Configuration->Sales->Payment methods->Ifthenpay->Active=No). And it appears on every other payment method (eg bank transfer).

**Comment by biojppm** [comment]
@manuelrocha88 ping

**Comment by manuelrocha88** [comment]
@biojppm pong

still investigating what happen... very very strange.

**Comment by biojppm** [comment]
@manuelrocha88 any news? were you able to reproduce this? Do you need further info?
thanks,
joao

**Comment by manuelrocha88** [comment]
Have already reproduce the problem and the strange thing is this problem has there all the time. Strange no one has complain about it or it was something that Magent changed on last versions...

Hope until the end of the week can fix the issue.

**Comment by biojppm** [comment]
ok, thanks!

**Comment by biojppm** [comment]
@manuelrocha88 any news?

**Comment by manuelrocha88** [comment]
@biojppm done
