### ISSUE TITLE
Missing logo in checkout 

### ISSUE THREAD

**Issue by palo** [manuelrocha88/magento2-Ifthenpay_Multibanco#3]
Tested in Magento CE 2.1.7 store and fresh install with demo data.
```
`[2017-06-20 08:09:27] main.CRITICAL: Broken reference: No element found with ID 'checkout.header.wrapper'. [] []
```
Symptoms:
Missing logo in one page checkout.
Header search and header cart visible in one page checkout

Similar problem in other payment modules was solved by changing layout from "1column" to "checkout" in [checkout_index_index.xml](https://github.com/manuelrocha88/magento2-Ifthenpay_Multibanco/blob/master/view/frontend/layout/checkout_index_index.xml#L13)

Thank you for making this extension available.
BR Paulo

**Comment by manuelrocha88** [comment]
@palo could you please check If it is working now in order to change the version? You just need to change that on your file.

**Comment by palo** [comment]
@manuelrocha88 Its working. Changed these files:

.../vendor/ifthenpay/multibanco-magento/view/frontend/layout/checkout_index_index.xml
.../vendor/ifthenpay/multibanco-magento/view/view/frontend/layout/checkout_index_index.xml
.../app/code/Ifthenpay/Multibanco/view/frontend/layout/checkout_index_index.xml
.../app/code/Ifthenpay/Multibanco/view/view/frontend/layout/checkout_index_index.xml
```

**Comment by manuelrocha88** [comment]
@palo can you make a pull request with those changes?



No dia 20/06/2017, às 10:07, palo <notifications@github.com> escreveu:
