### ISSUE TITLE
Erro em formatPrice($valor) nos invoices/ship/creditmemo

### ISSUE THREAD

**Issue by Divisum** [manuelrocha88/magento2-Ifthenpay_Multibanco#5]
Boas

No magento 2.2.x, quando tentamos formatar o valor nos invoices, a callprice() que deriva do formatPrice($valor) não está declarada.
Ficheiro: Ifthenpay/Multibanco/Block/Info/Multibanco.php
Line: 100

Cumprimentos

**Comment by marciio14** [comment]
Boas, 

Tive o mesmo problema num projeto e resolvi da seguinte maneira: 

Vai ao ficheiro:

/app/code/Ifthenpay/Multibanco/Block/Info/Multibanco.php

Depois acrescentas a seguinte função:

```
public function formatThePrice($valor){
        $valor = round($valor, 2);
        $valor = number_format($valor, 2);
        $valor = "€".$valor;

        return $valor;
}
```

E na função onde está a ser chamada a **formatPrice** alteras para o seguinte:

```
    public function getValorAdmin()
    {
        $valor = $this->getOrderAdmin()->getGrandTotal();

        if($valor == null){
            $order  = $this->getOrderAdmin()->getOrder();
            $valor = $order->getDataByKey("grand_total");
        }
        $valor = $this -> formatThePrice($valor);
        //return $this->getOrderAdmin()->formatPrice($valor);
        return $valor;
    }
```

Talvez não seja a melhor forma de resolver mas funcionou. 

Abraço

**Comment by manuelrocha88** [comment]
Problema resolvido com o commit e5f93f78c26377cf93c26efdf3192cc7c608f562
